obj-$(CONFIG_FPC_FINGERPRINT)		+= fpc/
obj-$(CONFIG_FPC_FINGERPRINT_CLOVER)+= fpc_clover/
obj-$(CONFIG_GOODIX_FINGERPRINT)	+= goodix/
obj-$(CONFIG_CDFINGER_FP)	+= cdfinger_X01BD/
obj-$(CONFIG_FOCALTECH_FP)	+= focaltech_X01BD/
